### ISSUE TITLE
Replace tokens pallet instance with assets

### ISSUE THREAD

**Issue by stanly-johnson** [valibre-org/vln-node#84]
Related [substrate/8483](https://github.com/paritytech/substrate/pull/8483)
Depends on [substrate/8453](https://github.com/paritytech/substrate/issues/8453) specifically `fungibles::Lockable`

**Comment by stanly-johnson** [comment]
Hi @olanod, I was looking at the assets pallet and it is more of a token generator/factory than a replacement for our current use case with orml-tokens. How should we handle this, is the goal to exactly emulate the function we previously had with orml-tokens (I guess via a wrapper pallet similar to backed-asset 🤔 ) or is the goal to allow anyone to create these tokens via deposit of a base currency? In that case do we implement balances pallet for the [currency](https://github.com/paritytech/substrate/blob/ea5d3570673d125dfe0b7da33b345c3c13195380/frame/assets/src/lib.rs#L185)?

**Comment by olanod** [comment]
True, assets pallet has more functionality as a "token factory" but not necessarily differs a lot from what we have. Any pallet that used to depend on a `MultiCurrency` ideally will depend on a [`fungibles::*`](https://github.com/paritytech/substrate/blob/master/frame/support/src/traits/tokens/fungibles.rs) trait with the needed granular functionality, same for anything depending on `Currecy` would instead depend on a [`fungible::*`](https://github.com/paritytech/substrate/blob/master/frame/support/src/traits/tokens/fungible.rs). When it comes to configuring the pallet, initially we only allow for the root origin to create asset classes similar to how statemine did at launch, it might be that we enable the asset creation by anyone in the future but since in our case a new fiat assets mean we should also have an oracle for its price its likely that it will remain restricted. The difference with how it is now with ORML would be that a new asset class(e.g. creating the EUR token) can be created more dynamically just issuing a transaction(e.g. by the Kusama council) instead of a more cumbersome runtime upgrade.

**Comment by stanly-johnson** [comment]
What about the currency, do we just use KSM/DOT like [statemint](https://github.com/paritytech/statemint/blob/903a7569f7ff5ca66848827a937a809a1b9eac21/node/src/chain_spec.rs#L227) or do we have our own?

**Comment by olanod** [comment]
Besides from the assets pallet itself, is there any other dependency on a `Currency`? Seems to me that if our instance of assets is controlled by the governance that wouldn't require reserving funds then a dummy adaptor can be created that implements currency without actually doing anything(the code paths in assets pallet where `Currency` is used shouldn't be needed.... Or the easy is we just add balances pallet for now and the token make it ROC or whatever the relay chain is.
